# Generated by Django 4.2.3 on 2023-07-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='art_store',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
    ]
