# Generated by Django 4.2.3 on 2023-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_rename_firstname_admin_name_remove_admin_art_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.CharField(max_length=200)),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('team3', models.CharField(max_length=200)),
                ('team4', models.CharField(max_length=200)),
                ('team5', models.CharField(max_length=200)),
                ('team6', models.CharField(max_length=200)),
                ('team7', models.CharField(max_length=200)),
                ('team8', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Compitition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
                ('image_url', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
