# Generated by Django 4.2.3 on 2023-07-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_cart_user_alter_order_user_alter_profile_id_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Items',
            new_name='items',
        ),
    ]
