# Generated by Django 4.2.3 on 2023-07-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_rename_items_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
